service: academic-community

provider:
  name: aws
  runtime: nodejs10.x
  stage: production
  region: eu-central-1
  memorySize: 128
  timeout: 30

  environment:
    PGUSER: ${ssm:GTUBT_DBUSER}
    PGPASSWORD: ${ssm:GTUBT_DBPASS}
    PGHOST: ${ssm:GTUBT_DBHOST}
    PGPORT: ${ssm:GTUBT_DBPORT}
    PGDATABASE: ${ssm:GTUBT_DBNAME}

functions:
  app:
    handler: app/app.handler
    events:
      - http:
          method: ANY
          path: /api/{proxy+}
          cors: true
    layers:
      - Ref: NodeModulesLambdaLayer

layers:
  NodeModules:
    name: node_modules
    path: layer
    description: Nodejs Modules
    compatibleRuntimes:
      - nodejs10.x

package:
  exclude:
    - node_modules/**
    - layer/**
    - .gitignore
    - .prettierrc
    - .git/**
    - yarn.lock
  include:

plugins:
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain:
    domainName: api.yildizozan.com
    basePath: ""
    stage: ${self:provider.stage}
    certificateName: "*.yildizozan.com"
    #certificateArn: arn:aws:acm:us-east-1:886175673370:certificate/b73a3892-96f8-4192-a888-710d656792dd
    createRoute53Record: false
  serverless-offline:
    httpsProtocol: "dev-certs"
    port: 4000
