service: gtubt

provider:
  name: aws
  runtime: nodejs10.x
  stage: production
  region: eu-central-1
  timeout: 30

  environment:
    PGUSER: ${ssm:GTUBT_DBUSER}
    PGPASSWORD: ${ssm:GTUBT_DBPASS}
    PGHOST: ${ssm:GTUBT_DBHOST}
    PGPORT: ${ssm:GTUBT_DBPORT}
    PGDATABASE: ${ssm:GTUBT_DBNAME}

functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /api/{proxy+}
    layers:
      - arn:aws:lambda:eu-central-1:${env:AWS_USERID}:layer:node_modules:${env:LAYER_VERSION}

package:
  exclude:
    - node_modules/**
    - layer/**
    - .gitignore
    - .prettierrc
    - .git/**
    - yarn.lock
  include:
